article: https://www.bigclown.com/doc/projects/radio-push-button/
video: https://youtu.be/OCPPKXzCBg0
images:
  - title:
    url: https://github.com/hardwario/website/blob/master/static/kits-images/push-button/main.png
assembly:
  - name: HARDWARIO Button Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Mini Battery Module
